// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  tutorialSidebar: [
    'ui-showcase',
    {
      type: 'autogenerated',
      dirName: '.',
    },
    {
      type: 'category',
      label: 'Introduction',
      items: [
        'intro/introduction',
        'intro/syllabus',
        'intro/hardware-setup',
        'intro/pedagogical-approach'
      ],
    },
    {
      type: 'category',
      label: 'Module 1: The Robotic Nervous System (Weeks 3-5)',
      items: [
        '01-module-1/00-module-overview',
        '01-module-1/01-ros2-fundamentals',
        '01-module-1/02-nodes-topics-services',
        '01-module-1/03-urdf-modeling',
        '01-module-1/04-rclpy-python',
        '01-module-1/05-digital-twin-simulation',
        '01-module-1/06-physical-deployment'
      ],
    },
    {
      type: 'category',
      label: 'Module 2: The Digital Twin (Weeks 6-7)',
      items: [
        '02-module-2/00-module-overview',
        '02-module-2/01-gazebo-physics',
        '02-module-2/02-unity-rendering',
        '02-module-2/03-sensor-integration',
        '02-module-2/04-lidar-depth-cameras',
        '02-module-2/05-digital-twin-exercises',
        '02-module-2/06-sim-to-real-transfer'
      ],
    },
    {
      type: 'category',
      label: 'Module 3: The AI-Robot Brain (Weeks 8-10)',
      items: [
        '03-module-3/00-module-overview',
        '03-module-3/01-nvidia-isaac-sim',
        '03-module-3/02-isaac-ros',
        '03-module-3/03-vslam-navigation',
        '03-module-3/04-nav2-systems',
        '03-module-3/05-reinforcement-learning',
        '03-module-3/06-digital-twin-training',
        '03-module-3/07-physical-deployment'
      ],
    },
    {
      type: 'category',
      label: 'Module 4: Vision-Language-Action (Weeks 11-13)',
      items: [
        '04-module-4/00-module-overview',
        '04-module-4/01-vision-language-action',
        '04-module-4/02-whisper-audio-processing',
        '04-module-4/03-llm-cognitive-planning',
        '04-module-4/04-autonomous-humanoid-capstone',
        '04-module-4/05-simulated-capstone-project',
        '04-module-4/06-physical-capstone-deployment'
      ],
    },
    {
      type: 'category',
      label: 'Capstone Project',
      items: [
        'capstone/project-overview',
        'capstone/team-formation',
        'capstone/milestone-tracking',
        'capstone/evaluation-criteria'
      ],
    },
    {
      type: 'category',
      label: 'Test Pages',
      items: [
        '98-test-phase-12-features',
        '99-test-content-enhancement'
      ],
    }
  ],
};

module.exports = sidebars;