from fastapi import APIRouter, HTTPException, Depends, Request
import logging
from typing import Optional
import os
from ...models.request import MessageRequest
from ...models.response import MessageResponse, ErrorResponse
from ...services.chat_service import chat_service
from ..middleware.auth import verify_api_key


router = APIRouter()
logger = logging.getLogger(__name__)


@router.post("/chat", response_model=MessageResponse, summary="Send a chat message")
async def chat_endpoint(
    request: MessageRequest,
) -> MessageResponse:
    """
    Process a chat message and return an AI-generated response.

    This endpoint accepts a user message and returns a response generated by
    the Groq AI model through the OpenAI SDK integration.
    """
    try:
        logger.info(f"Received chat request for conversation: {request.conversation_id}")

        # Validate the request
        await chat_service.validate_request(request)

        # Process the message using the chat service
        response = await chat_service.process_message(request)

        logger.info(f"Returning response for conversation: {response.conversation_id}")
        return response

    except ValueError as ve:
        logger.warning(f"Validation error: {str(ve)}")
        raise HTTPException(status_code=400, detail=str(ve))

    except RuntimeError as re:
        logger.error(f"Runtime error in chat processing: {str(re)}")
        raise HTTPException(status_code=500, detail=f"Internal service error: {str(re)}")

    except HTTPException:
        # Re-raise HTTP exceptions as-is
        raise

    except Exception as e:
        logger.error(f"Unexpected error in chat endpoint: {str(e)}", exc_info=True)
        raise HTTPException(status_code=500, detail="An unexpected error occurred")


# Health check for the router
@router.get("/chat/health", summary="Chat endpoint health check")
async def chat_health() -> dict:
    """Health check for the chat endpoint."""
    from ...config import settings
    return {"status": "chat service healthy", "model": settings.groq_model}